import { createSlice } from "@reduxjs/toolkit";

// Create a new slice of the Redux store called "weather"
const weatherSlice = createSlice({
  name: 'weather', // Name of the slice
  initialState: { // Initial state of the slice
    city: '',
    country: ''
  },
  reducers: {
    // Define a new action called "addDate"
    addDate: (state, action) => {
      // Update the state with the city and country values from the action payload
      state.city = action.payload.city;
      state.country = action.payload.country;
    }
  }
})

// Export the "addDate" action from the slice
export const { addDate } = weatherSlice.actions;

// Export the reducer function generated by the slice
export default weatherSlice.reducer;